apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
      - name: trips
        image: registryefd3942.azurecr.io/tripinsights/trips:1.0
        ports:
        - containerPort: 80
        env:
        - name: OPENAPI_DOCS_URI
          value: 'http://localhost'
        - name: PORT
          value: '80'
        - name: DEBUG_LOGGING
          value: 'true
        envFrom:
          - secretRef:
             name: sql-info
---
apiVersion: v1
kind: Service
metadata:
  name: trips-service
spec:
  selector:
    app: trips
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
