apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:  
      containers:
      - name: poi
        image: registryefd3942.azurecr.io/tripinsights/poi:1.0
        ports:
        - containerPort: 80
        env:
        - name: WEB_SERVER_BASE_URI
          value: 'http://0.0.0.0'
        - name: WEB_PORT
          value: '80'
        - name: ASPNETCORE_ENVIRONMENT
          value: 'Production'
        volumeMounts:
        - name: kv-oh42-mnt
          mountPath: "/secrets"
          readOnly: true
      volumes:
        - name: kv-oh42-mnt
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: kv-oh42
---
apiVersion: v1
kind: Service
metadata:
  name: poi-service
spec:
  selector:
    app: poi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
