apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: kv-oh42
spec:
  provider: azure
  parameters:
    keyvaultName: "kv-oh42"       # The name of the Azure Key Vault
    useVMManagedIdentity: "true"         
    userAssignedIdentityID: "4dc1b2a8-fda8-4afc-a880-2d7502808d05" # The clientId of the addon-created managed identity
    cloudName: ""                         # [OPTIONAL for Azure] if not provided, Azure environment will default to AzurePublicCloud 
    objects:  |
      array:
        - |
          objectName: SQLSERVER       # In this example, 'ExampleSecret'   
          objectAlias: "SQL_SERVER"
          objectType: secret              # Object types: secret, key or cert
        - |
          objectName: SQLUSER       # In this example, 'ExampleSecret'   
          objectAlias: "SQL_USER"
          objectType: secret              # Object types: secret, key or cert
        - |
          objectName: SQLPASSWORD       # In this example, 'ExampleSecret'   
          objectAlias: "SQL_PASSWORD"
          objectType: secret              # Object types: secret, key or cert
        - |
          objectName: SQLDBNAME       # In this example, 'ExampleSecret'   
          objectAlias: "SQL_DBNAME"
          objectType: secret              # Object types: secret, key or cert
    tenantId: "8108d9c7-f473-47e3-903e-096fb86ddb2f"          # the tenant ID containing the Azure Key Vault instance
